---
- hosts: all
  become: true
  tasks:
    - name: update apt and upgrade all packages
      apt: 
        upgrade: yes
        update_cache: yes

    - name: install nginx latest version
      apt: name=nginx state=latest
      
    - name: start nginx
      service:
        name: nginx
        state: started
        
